# Kanagawa theme
# https://github.com/rebelot/kanagawa.nvim/blob/master/extras/alacritty_kanagawa.yml
#
# MIT License
#
# Copyright (c) 2021 Tommaso Laurenzi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

[colors.primary]
background = '0x1f1f28'
foreground = '0xdcd7ba'

[colors.normal]
black = '0x090618'
red = '0xc34043'
green = '0x76946a'
yellow = '0xc0a36e'
blue = '0x7e9cd8'
magenta = '0x957fb8'
cyan = '0x6a9589'
white = '0xc8c093'

[colors.bright]
black = '0x727169'
red = '0xe82424'
green = '0x98bb6c'
yellow = '0xe6c384'
blue = '0x7fb4ca'
magenta = '0x938aa9'
cyan = '0x7aa89f'
white = '0xdcd7ba'

[colors.selection]
background = '0x2d4f67'
foreground = '0xc8c093'

[[colors.indexed_colors]]
index = 16
color = '0xffa066'

[[colors.indexed_colors]]
index = 17
color = '0xff5d62'
