"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Oleksii Orlenko"
email = "alex@aqrln.net"

[git]
subprocess = true

[signing]
behavior = "own"
backend = "ssh"
key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICJNVFYoy4BuuFkv3jqiFzti+IkGA0dUW0DnJr6dxl+T"
backends.ssh.program = "/opt/1Password/op-ssh-sign"

[templates]
git_push_bookmark = '"aqrln-" ++ change_id.short()'

[aliases]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
